#!/bin/bash

REMOTE="Jonathan@lenovo-legion"

# todo logic to ensure script is run as root
./replicate-with-rsync 0 "/tank0/ds0/@cache"           "${REMOTE}:/cygdrive/e/ds0/@cache"
./replicate-with-rsync 0 "/tank0/ds0/@files"           "${REMOTE}:/cygdrive/e/ds0/@files"
./replicate-with-rsync 0 "/tank0/ds0/@homeassistant"   "${REMOTE}:/cygdrive/e/ds0/@homeassistant"
./replicate-with-rsync 0 "/tank0/ds0/@iso"             "${REMOTE}:/cygdrive/e/ds0/@iso"
./replicate-with-rsync 0 "/tank0/ds0/@isponsorblocktv" "${REMOTE}:/cygdrive/e/ds0/@isponsorblocktv"
./replicate-with-rsync 0 "/tank0/ds0/@mealie"          "${REMOTE}:/cygdrive/e/ds0/@mealie"
./replicate-with-rsync 0 "/tank0/ds0/@odoo.root"       "${REMOTE}:/cygdrive/e/ds0/@odoo.root"
./replicate-with-rsync 0 "/tank0/ds0/@photos"          "${REMOTE}:/cygdrive/e/ds0/@photos"
./replicate-with-rsync 0 "/tank0/ds0/@resilio-sync"    "${REMOTE}:/cygdrive/e/ds0/@resilio-sync"
./replicate-with-rsync 0 "/tank0/ds0/@shared-files"    "${REMOTE}:/cygdrive/e/ds0/@shared-files"
./replicate-with-rsync 0 "/tank0/ds0/@ssh"             "${REMOTE}:/cygdrive/e/ds0/@ssh"
./replicate-with-rsync 0 "/tank0/ds0/@ssh-for-windows" "${REMOTE}:/cygdrive/e/ds0/@ssh-for-windows"
./replicate-with-rsync 0 "/tank0/ds0/@stirling-pdf"    "${REMOTE}:/cygdrive/e/ds0/@stirling-pdf"
./replicate-with-rsync 0 "/tank0/ds0/@syncthing"       "${REMOTE}:/cygdrive/e/ds0/@syncthing"
./replicate-with-rsync 0 "/tank0/ds0/@timetagger"      "${REMOTE}:/cygdrive/e/ds0/@timetagger"
./replicate-with-rsync 0 "/tank0/ds0/@vault"           "${REMOTE}:/cygdrive/e/ds0/@vault"
./replicate-with-rsync 0 "/tank0/ds0/@vikunja"         "${REMOTE}:/cygdrive/e/ds0/@vikunja"
./replicate-with-rsync 0 "/tank0/ds0/@windows-files"   "${REMOTE}:/cygdrive/e/ds0/@windows-files"

# Replication tasks that require hardlink support (slow):
./replicate-with-rsync 1 "/tank0/ds0/@media"           "${REMOTE}:/cygdrive/e/ds0/@media"
