services:
    tamari:
        image: alexbates/tamari:1.0
        container_name: tamari
        ports:
            - 41964:4888
        volumes:
            - /mnt/pool/db/tamari/appdata:/app/appdata
        restart: unless-stopped
