services:
  isponsorblocktv:
    # Configuration tool: https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    container_name: isponsorblocktv
    # environment:
    #   - TZ=America/Los_Angeles
    # network_mode: host
    volumes:
    - /mnt/pool/db/isponsorblocktv/data:/app/data
    restart: unless-stopped
