# include:
#   - docker/compose/flaresolverr.yml
#   - docker/compose/gluetun.yml
#   - docker/compose/prowlarr.yml
#   - docker/compose/qbittorrent.yml
#   - docker/compose/radarr.yml
#   - docker/compose/recyclarr.yml
#   - docker/compose/sonarr.yml

services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - SERVER_COUNTRIES=Sweden
      - TZ=America/Los_Angeles
    env_file:
      - /mnt/pool/media/starr/gluetun/password.env
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6767:6767 # bazarr
      # - 8191:8191 # flaresolverr
      - 8686:8686 # lidarr
      - 8090:8090 # mylar3
      # - 9696:9696 # prowlarr
      - 16718:16718 # qbittorrent
      # - 7878:7878 # radarr
      - 8787:8787 # readarr
      # - 8989:8989 # sonarr
    restart: unless-stopped

  flaresolverr:
    # Image:            ghcr.io/flaresolverr/flaresolverr:latest
    # DockerHub mirror: flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on:
      - gluetun
    environment:
      - CAPTCHA_SOLVER=none # see: https://github.com/FlareSolverr/FlareSolverr?tab=readme-ov-file#captcha-solvers
      - LOG_HTML=false
      - LOG_LEVEL=info
      - TZ=America/Los_Angeles
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - gluetun
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=America/Los_Angeles
    ports:
      - 9696:9696
    volumes:
      - /mnt/pool/media/starr/prowlarr:/config
    restart: unless-stopped

  qbittorrent:
    # qbt behind reverse-proxy: https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/32#issuecomment-898141958
    # image: lscr.io/linuxserver/qbittorrent:4.6.6
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=America/Los_Angeles
      - WEBUI_PORT=16718 # see: https://docs.linuxserver.io/images/docker-qbittorrent/#webui_port-variable
      # Due to issues with CSRF and port mapping, should you require to alter the port for the webui you need to change both sides of the -p 8080 switch AND set the WEBUI_PORT variable to the new port.
    # ports:
    #   - 8080:8080
    network_mode: "service:gluetun"
    volumes:
      - /mnt/pool/media/starr/qbittorrent:/config
      - /mnt/pool/media/downloads:/data/downloads # see: https://wiki.servarr.com/sonarr/system#docker-bad-remote-path-mapping
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - gluetun
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=America/Los_Angeles
    ports:
      - 7878:7878
    volumes:
      - /mnt/pool/media/starr/radarr:/config
      - /mnt/pool/media:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    depends_on:
      - gluetun
    environment:
      - CRON_SCHEDULE=@daily
      # - RECYCLARR_CREATE_CONFIG=true # more info: https://recyclarr.dev/wiki/installation/docker/
      - TZ=America/Los_Angeles
    user: 3001:3001
    volumes:
      - /mnt/pool/media/starr/recyclarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - gluetun
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=America/Los_Angeles
    ports:
      - 8989:8989
    volumes:
      - /mnt/pool/media/starr/sonarr:/config
      - /mnt/pool/media:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped
