#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - 7575:7575
    volumes:
      - ${HOMARR_VOLUME_CONFIGS}:/app/data/configs
      - ${HOMARR_VOLUME_DATA}:/data
      - ${HOMARR_VOLUME_ICONS}:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
    restart: unless-stopped
