services:
  isponsorblocktv:
    # Configuration tool: https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    container_name: isponsorblocktv
    environment:
      - TZ=${TZ}
    volumes:
    - ${ISBTV_VOLUME_DATA}:/app/data
    restart: unless-stopped
