services:
  grocy:
    image: lscr.io/linuxserver/grocy:4.5.0
    container_name: grocy
    environment:
      # - PUID=568
      # - PGID=568
      - PUID=${OPERATOR_PUID}
      - PGID=${OPERATOR_PGID}
      - TZ=${TZ}
    ports:
      - 30451:80
    volumes:
      - ${GROCY_VOLUME_CONFIG}:/config
    restart: unless-stopped
