services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.27.10
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    hostname: syncthing #optional
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ${SYNCTHING_VOLUME_CONFIG}:/config
      - ${SYNCTHING_VOLUME_DATA}:${SYNCTHING_VOLUME_DATA} # avoids having to specify share paths both in syncthing web gui AND in here
      # - ${DATA1_HOST}:${DATA1_CONTAINER}
      # - ${DATA1_HOST}:${DATA1_CONTAINER}
    restart: unless-stopped
