services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - DOCKER_USER=0
    user: 0:0
    volumes:
      - '/mnt/pool/config/code:/root/.config'
      # - $PWD:/home/coder/project # add project dir here
    ports:
      - 37747:8080
    tty: true
    stdin_open: true
