services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
      - TZ=America/Los_Angeles
    ports:
      - 30343:8080 # NOTE: 8080 taken by qbittorrent
    volumes:
      - /mnt/pool/db/stirling-pdf/tessdata:/usr/share/tessdata #Required for extra OCR languages
      - /mnt/pool/db/stirling-pdf/extra-configs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    restart: unless-stopped
