services:
  code:
    container_name: code
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - PASSWORD=makomako06
      - PROXY_DOMAIN=code.sixducks.org
      - DEFAULT_WORKSPACE=/workspace
    image: lscr.io/linuxserver/code-server:latest
    ports:
      - '8443:8443'
    restart: unless-stopped
    volumes:
      - /mnt/pool/db/code:/config
      - /mnt/pool/git/cluster:/workspace
