services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    environment:
      - INIT_ASSETS=1 # default
    ports:
      - 8080:8080
    user: 0:0 # 1000:1000
    volumes:
      - ${HOMER_VOLUME_ASSETS}:/www/assets
    restart: unless-stopped
