services:
  qbittorrent-alt:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-alt
    depends_on:
      - gluetun-alt
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBA_PORT} # see: https://docs.linuxserver.io/images/docker-qbittorrent/#webui_port-variable
    # ports:
    #   - 8080:8080
    network_mode: "service:gluetun-alt"
    volumes:
      - ${QBITTORRENT_ALT_VOLUME_CONFIG}:/config
      - ${QBITTORRENT_ALT_VOLUME_DOWNLOADS}:/data/downloads # see: https://wiki.servarr.com/sonarr/system#docker-bad-remote-path-mapping
    restart: unless-stopped
