include:
  - docker-compose/audiobookshelf.yml
  - docker-compose/download-audio-stream-wfpk.yml
  - docker-compose/homeassistant.yml
  - docker-compose/jellyfin.yml
  - docker-compose/jellyfin-music.yml
  - docker-compose/polaris.yml
  - docker-compose/resilio-sync.yml
  - docker-compose/timetagger.yml
  - docker-compose/vikunja.yml
