include:
  - docker-compose.download-audio-stream-wfpk.yml
  - docker-compose.jellyfin.yml
  - docker-compose.polaris.yml
  - docker-compose.portainer.yml
  - docker-compose.resilio-sync.yml
  - docker-compose.vikunja.yml
