services:
  sonarr-alt:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-alt
    depends_on:
      - gluetun-alt
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    # ports:
    #   - 8989:8989
    network_mode: "service:gluetun-alt"
    volumes:
      - ${SONARR_ALT_VOLUME_CONFIG}:/config
      - ${SONARR_ALT_VOLUME_DATA}:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped
