services:
  download-audio-stream:
    image: download-audio-stream
    build: local/download-audio-stream
    container_name: ${DOWNLOAD_AUDIO_STREAM_CONTAINER_NAME}
    environment:
      - DURATION=${DOWNLOAD_AUDIO_STREAM_DURATION}
      - OUTPUT_FILE_BASENAME=${DOWNLOAD_AUDIO_STREAM_OUTPUT_FILE_BASENAME}
      - URL=${DOWNLOAD_AUDIO_STREAM_URL}
    volumes:
      - ${DOWNLOAD_AUDIO_STREAM_VOLUME_CRONJOBS}:/etc/crontabs/root
      - ${DOWNLOAD_AUDIO_STREAM_VOLUME_OUTPUT}:/output
    restart: unless-stopped
