services:
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    # depends_on:
    #   - gluetun
    environment:
      - TZ=${TZ}
    env_file:
      - ${NOTIFIARR_ENV_PASSWORDS}
    hostname: notifiarr
    ports:
      - 5454:5454
    # network_mode: "service:gluetun"
    volumes:
      - ${NOTIFIARR_VOLUME_CONFIG}:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped
