services:
  gluetun-alt:
    image: qmcgaw/gluetun
    container_name: gluetun-alt
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - SERVER_COUNTRIES=Netherlands
      - TZ=${TZ}
    env_file:
      - ${HOME}/.config/gluetun/password.env
    ports:
      - 6882:6881
      - 6882:6881/udp
      - 6768:6767 # bazarr
      - 8192:8191 # flaresolverr
      - 9697:9696 # prowlarr
      - ${QBA_PORT}:${QBA_PORT} # qbittorrent
      - 7879:7878 # radarr
      - 8990:8989 # sonarr
    restart: unless-stopped
