services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    # ports:
    #   - 9696:9696
    volumes:
      - ${PROWLARR_VOLUME_CONFIG}:/config
    restart: unless-stopped
