services:
  notifiarr-alt:
    image: golift/notifiarr
    container_name: notifiarr-alt
    # depends_on:
    #   - gluetun
    environment:
      - PUID=${PUID} # NOTE: appears not to respect
      - PGID=${GUID} # NOTE: appears not to respect
      - TZ=${TZ}
    env_file:
      - ${NOTIFIARR_ALT_ENV_PASSWORDS}
    hostname: notifiarr-alt
    ports:
      - 5455:5454
    # network_mode: "service:gluetun"
    volumes:
      - ${NOTIFIARR_ALT_VOLUME_CONFIG}:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped
