#!/bin/bash

set -e

WORKDIR="$(dirname "$0")" && \
cd "$WORKDIR"

# Syntax: hooks/docker-compose <DOCKER-COMPOSE PROJECT NAME> <OPERATION> <SUB-OPERATION>
hooks/docker-compose DEFAULT up begin && \
docker compose up --detach && \
pid=$! && \
hooks/docker-compose DEFAULT up end

wait $pid && \
hooks/docker-compose DEFAULT down end
