#!/bin/bash

#############################
#                           #
#          EXAMPLE          #
#                           #
#############################

# sync-data 0 '/pool/ds.raspberry-pi/'      'Jonathan@lenovo-legion:/cygdrive/e/ds.raspberry-pi/'
# sync-data 1 '/pool/ds.raspberry-pi/media' 'Jonathan@lenovo-legion:/cygdrive/e/ds.raspberry-pi/media/' # here's a second pass on 'media' for hardlinks (slow)

#######################################
#                                     #
#          BEGIN USER CONFIG          #
#                                     #
#######################################
