services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      # - DOCKER_MODS=linuxserver/mods:universal-calibre # Optional & x86-64 only Adds the ability to perform ebook conversion
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 # Optionally set this to allow Google OAUTH to work
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    ports:
      - 8083:8083
    volumes:
      - ${CALIBRE_VOLUME_CONFIG}:/config
      - ${CALIBRE_VOLUME_BOOKS}:/books
    restart: unless-stopped
