services:
  immich-redis:
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    container_name: immich-redis
    environment:
      - TZ=${TZ}
    env_file:
      - ${IMMICH_ENV_FILE}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
