# NOTE: Intended for split-setup with a jellyfin instance for scanning
# media / writing metadata, and another instance for transcoding (presumably
# this instance will run on a personal machine with a GPU). The metadata
# instance requires persistent storage. The transcode instance only needs a
# docker volume.

services:
  jellyfin-transcode:
    image: lscr.io/linuxserver/jellyfin:10.9.9
    container_name: jellyfin-transcode
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - config:/config
      - data:/data
    restart: unless-stopped

volumes:
  config:
  data:
    driver: local
    driver_opts:
      type: cifs
      device: "//smb.nas.sixducks.duckdns.org/media"
      o: "username=xxxx,password=yyyy"

      # todo make sure to mount in readonly mode

      # todo make generic docker user with generic docker password? THAT can be saved securely in your git repo 

      # more info: https://stackoverflow.com/questions/75926725/how-to-secure-credentials-for-cifs-volume-in-docker-stack-secrets

      # todo just make the volume with a wizard bash script, password can be passed once and it never has to touch your repo (comment-out above volume definition)
