services:
  lidarr:
    # image: lscr.io/linuxserver/lidarr:2.4.3.4248-ls6
    image: lscr.io/linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    # ports:
    #   - 8686:8686
    network_mode: "service:gluetun"
    volumes:
      - ${LIDARR_VOLUME_CONFIG}:/config
      - ${LIDARR_VOLUME_DATA}:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped
