services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:nightly-9e283397-ls437
    container_name: mylar3
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    # ports:
    #   - 8090:8090
    network_mode: "service:gluetun"
    volumes:
      - ${MYLAR3_VOLUME_CONFIG}:/config
      - ${MYLAR3_VOLUME_DATA}:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped
