services:
  polaris:
    image: ogarcia/polaris
    container_name: polaris
    environment:
      - TZ=${TZ}
    ports:
      - 5050:5050
    volumes:
      - ${POLARIS_VOLUME_MUSIC}:/music
      - ${POLARIS_VOLUME_CACHE}:/var/cache/polaris
      - ${POLARIS_VOLUME_DATA}:/var/lib/polaris
    restart: unless-stopped
