services:
  readarr:
    # image: lscr.io/linuxserver/readarr:develop-0.3.32.2587-ls122
    image: lscr.io/linuxserver/readarr:latest
    container_name: readarr
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    # ports:
    #   - 8787:8787
    network_mode: "service:gluetun"
    volumes:
      - ${READARR_VOLUME_CONFIG}:/config
      - ${READARR_VOLUME_DATA}:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped
