services:
  tailscale-agent:
    image: tailscale/tailscale:latest
    container_name: tailscale-agent
    cap_add:
      - net_admin
      - sys_module
    environment:
      # TS_AUTHKEY: Connect this container to your tailnet
      # - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TZ=${TZ}
    env_file:
      - ${TAILSCALE_ENV_FILE}
    # hostname: ${NGINX_TS_HOSTNAME} # This is how your container will appear in your tailnet's machine list (commenting this line out, we're trying for dynamically-generated hostnames)
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

volumes:
  tailscale-state:
