# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    environment:
      TZ: ${TZ}
      DNSMASQ_LISTENING: all # needed if running in docker's default bridge network mode
      # WEBPASSWORD: pihole # set a secure password here or it will be random
    env_file:
      - ${PIHOLE_ENV_FILE}
    # networks:
    #   net:
    #     ipv4_address: ${PIHOLE_IP_ADDRESS} # NOTE: access the pihole web gui at <ip_address>/admin
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp" # NOTE: omv listens on port 80
    volumes:
      - ${PIHOLE_VOLUME_CONFIG_PIHOLE}:/etc/pihole
      - ${PIHOLE_VOLUME_CONFIG_DNSMASQ}:/etc/dnsmasq.d
    restart: unless-stopped

# networks:
#   net:
#     driver: macvlan
#     driver_opts:
#       parent: end0 # somethign something omv-managed network interfaces... :)
#     ipam:
#       config:
#         - subnet: 192.168.1.0/24 # your router's address range
#           gateway: 192.168.1.1   # NOTE: lack of dash is significant
